### ISSUE TITLE
deploy halted

### ISSUE THREAD

**Issue by raynamharris** [raynamharris/musicalgenes#11]
i could deploy it yesterday but not any more :(

```
Preparing to deploy application...DONE
Uploading bundle for application: 1885054...Error in force(code) : Could not upload file.
Calls: <Anonymous> -> withStatus -> force
Execution halted
```

**Comment by raynamharris** [comment]
fixed with https://github.com/raynamharris/musicalgenes/commit/e57cd48c769e9e88c27b4e1737ffad4cf41ed35b

**Comment by lexie-lee** [comment]
I met the same problems... when I try to deploy ,can you explain  how you solve the problems?
Thanks a lot !

This is the error info:

>  Unable to find repository URL for package rsvd
Error in force(code) : Could not upload file.
Calls: <Anonymous> -> withStatus -> force

**Comment by raynamharris** [comment]
I'm not sure exactly what is going on, but I had a pdf file in the repo that was causing problem, so I changed the yml heading in a Rmd script from `output: pdf_document` to 

```
output:
  pdf_document: default
  html_document: default
```

Then (and I'm not sure if I did this manually or if it was automatic, but I added `paper.pdf` to the list of files to avoid in the dcf file:

```
ignoredFiles: paper.pdf|.binder/install.R|.binder/runtime.txt
```

**Comment by raynamharris** [comment]
@lexie-lee  I'm not sure exactly what is going on, but I had a pdf file in the repo that was causing problem, so I changed the yml heading in a Rmd script from `output: pdf_document` to

```
output:
  pdf_document: default
  html_document: default
```

Then (and I'm not sure if I did this manually or if it was automatic, but I added paper.pdf to the list of files to avoid in the dcf file:

```
ignoredFiles: paper.pdf|.binder/install.R|.binder/runtime.txt
```
