### ISSUE TITLE
Gene Request: GnIH

### ISSUE THREAD

**Issue by vsfarrar** [raynamharris/musicalgenes#9]
Please provide the following useful information for one or more genes and we will add them. Thank you!

- Gene name: Gonadotropin inhibitory hormone 
- Gene abbreviation: GnIH
- Useful links:
In C.livia, the NCBI accession number is MG589638.1

**Comment by raynamharris** [comment]
okay, I found that GnIH is sometimes referred to as pro-FMRFamide-related neuropeptide VF precursor or NPVF. It has now been added. Thanks for the suggestion!!

![Screen Shot 2020-09-10 at 4 42 06 PM](https://user-images.githubusercontent.com/7544197/92827848-34314480-f387-11ea-87ce-eab97bcdc68a.png)
![Screen Shot 2020-09-10 at 4 59 28 PM](https://user-images.githubusercontent.com/7544197/92827854-35fb0800-f387-11ea-8658-526ac59c50d8.png)
